In [ ]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.preprocessing import LabelEncoder

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["species"] = iris.target_names[iris.target]

print("Iris dataset loaded successfully.")

Iris dataset loaded successfully.

In [ ]:
print("First 5 rows of the dataset:")
df.head()

First 5 rows of the dataset:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [ ]:
print("Last 5 rows of the dataset:")
df.tail()

Last 5 rows of the dataset:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [ ]:
print("Dataset Shape:", df.shape)

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Dataset Shape: (150, 5)
Number of Rows: 150
Number of Columns: 5

In [ ]:
print("Dataset Information:")
df.info()

print("\nData Types:")
print(df.dtypes)

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Data Types:
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species               object
dtype: object

In [ ]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

print("\nTotal Missing Values:")
print(df.isnull().sum().sum())

Missing Values in Each Column:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

Total Missing Values:
0

In [ ]:
duplicate_count = df.duplicated().sum()

print("Number of Duplicate Rows:", duplicate_count)

Number of Duplicate Rows: 1

In [ ]:
duplicates = df[df.duplicated()]

if len(duplicates) == 0:
    print("No duplicate records found.")
else:
    print("Duplicate records found:")
    display(duplicates)

Duplicate records found:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
142,5.8,2.7,5.1,1.9,virginica

In [ ]:
df_clean = df.drop_duplicates().copy()

print("Original Dataset Shape:", df.shape)
print("Dataset Shape After Removing Duplicates:", df_clean.shape)

Original Dataset Shape: (150, 5)
Dataset Shape After Removing Duplicates: (149, 5)

In [ ]:
print("Missing Values After Cleaning:")
print(df_clean.isnull().sum())

print("\nTotal Missing Values:",
      df_clean.isnull().sum().sum())

Missing Values After Cleaning:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

Total Missing Values: 0

In [ ]:
print("Statistical Summary:")
df_clean.describe()

Statistical Summary:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,149.000000,149.000000,149.000000,149.000000
mean,5.843624,3.059732,3.748993,1.194631
std,0.830851,0.436342,1.767791,0.762622
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.300000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [ ]:
print("Number of Flowers in Each Species:")
print(df_clean["species"].value_counts())

Number of Flowers in Each Species:
species
setosa        50
versicolor    50
virginica     49
Name: count, dtype: int64

In [ ]:
X = df_clean.drop("species", axis=1)
y = df_clean["species"]

print("Feature Columns:")
print(X.columns.tolist())

print("\nTarget Variable:")
print("species")

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)

Feature Columns:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Variable:
species

X Shape: (149, 4)
y Shape: (149,)

In [ ]:
label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Species Classes:")
print(label_encoder.classes_)

print("\nFirst 10 Encoded Target Values:")
print(y_encoded[:10])

Species Classes:
['setosa' 'versicolor' 'virginica']

First 10 Encoded Target Values:
[0 0 0 0 0 0 0 0 0 0]

In [ ]:
df_clean["species_encoded"] = y_encoded

print("Dataset with Encoded Target:")
df_clean.head()

Dataset with Encoded Target:

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,species_encoded
0,5.1,3.5,1.4,0.2,setosa,0
1,4.9,3.0,1.4,0.2,setosa,0
2,4.7,3.2,1.3,0.2,setosa,0
3,4.6,3.1,1.5,0.2,setosa,0
4,5.0,3.6,1.4,0.2,setosa,0

In [ ]:
print("=" * 50)
print("FINAL PREPROCESSED DATASET")
print("=" * 50)

print("Rows:", df_clean.shape[0])
print("Columns:", df_clean.shape[1])
print("Missing Values:", df_clean.isnull().sum().sum())
print("Duplicate Rows:", df_clean.duplicated().sum())

print("\nFeature Shape:", X.shape)
print("Target Shape:", y_encoded.shape)

print("\nPreprocessing completed successfully.")

==================================================
FINAL PREPROCESSED DATASET
==================================================
Rows: 149
Columns: 6
Missing Values: 0
Duplicate Rows: 0

Feature Shape: (149, 4)
Target Shape: (149,)

Preprocessing completed successfully.

Data Collection and Preprocessing
The Iris dataset was loaded using the Scikit-learn library and converted into a Pandas DataFrame for analysis. The dataset contains four numerical input features: sepal length, sepal width, petal length and petal width. The target variable represents the Iris flower species.
The first and last five records were inspected using head() and tail(). The shape, data types and general information of the dataset were also examined. Missing values and duplicate records were checked to identify potential data-quality issues. Duplicate records, if present, were removed to create a clean dataset.
The input features were separated from the target variable. Since the target originally contains categorical species names, Label Encoding was used to convert Setosa, Versicolor and Virginica into numerical class labels suitable for machine-learning algorithms.
The resulting dataset is now cleaned, structured and ready for exploratory data analysis and model development.