In [1]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["species"] = iris.target_names[iris.target]

print("Iris dataset loaded successfully.")
print("Original shape:", df.shape)

df.head()

Iris dataset loaded successfully.
Original shape: (150, 5)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [3]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates().copy()

print("Shape after cleaning:", df.shape)

Missing values: 0
Duplicate rows: 1
Shape after cleaning: (149, 5)

In [4]:
X = df.drop("species", axis=1)
y = df["species"]

print("Feature Variables:")
print(X.columns.tolist())

print("\nTarget Variable:")
print("species")

print("\nX Shape:", X.shape)
print("y Shape:", y.shape)

Feature Variables:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Variable:
species

X Shape: (149, 4)
y Shape: (149,)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)

print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Features Shape: (119, 4)
Testing Features Shape: (30, 4)
Training Samples: 119
Testing Samples: 30

In [6]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

print("Random Forest Classifier created successfully.")
print("Number of Trees:", model.n_estimators)

Random Forest Classifier created successfully.
Number of Trees: 100

Model Selection: Random Forest Classifier
Random Forest was selected because the Iris flower problem is a multiclass classification problem. Random Forest combines multiple decision trees and uses their results to produce a final prediction.
It is suitable for this dataset because it can learn both simple and non-linear relationships between numerical features such as sepal length, sepal width, petal length and petal width. It also works directly with multiclass target variables and does not require feature scaling.
Random Forest is generally robust, easy to train and performs effectively on small structured datasets such as Iris.

In [7]:
model.fit(
    X_train,
    y_train
)

print("Model training completed successfully.")

Model training completed successfully.

In [8]:
print("Model Type:")
print(type(model).__name__)

print("\nNumber of Trees:")
print(model.n_estimators)

print("\nClasses learned by the model:")
print(model.classes_)

Model Type:
RandomForestClassifier

Number of Trees:
100

Classes learned by the model:
['setosa' 'versicolor' 'virginica']

In [9]:
predictions = model.predict(X_test)

print("Predictions generated successfully.")
print("Number of Predictions:", len(predictions))

Predictions generated successfully.
Number of Predictions: 30

In [10]:
prediction_results = pd.DataFrame({
    "Actual Species": y_test.values,
    "Predicted Species": predictions
})

print("Sample Predictions:")

prediction_results.head(10)

Sample Predictions:

  Actual Species Predicted Species
0     versicolor        versicolor
1     versicolor        versicolor
2      virginica         virginica
3         setosa            setosa
4      virginica         virginica
5     versicolor        versicolor
6     versicolor        versicolor
7         setosa            setosa
8      virginica         virginica
9      virginica         virginica

In [11]:
new_flower = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=X.columns
)

new_prediction = model.predict(new_flower)

print("New Flower Measurements:")
print(new_flower)

print("\nPredicted Species:")
print(new_prediction[0])

New Flower Measurements:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2

Predicted Species:
setosa

In [12]:
feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print("Feature Importance:")
feature_importance

Feature Importance:

             Feature  Importance
3   petal width (cm)    0.439768
2  petal length (cm)    0.416405
0  sepal length (cm)    0.114842
1   sepal width (cm)    0.028985

In [13]:
print("=" * 55)
print("TASK 4: MODEL DEVELOPMENT & TRAINING COMPLETED")
print("=" * 55)

print("Dataset              : Iris Flower Dataset")
print("Problem Type         : Multiclass Classification")
print("Algorithm            : Random Forest Classifier")
print("Number of Trees      : 100")
print("Training Samples     :", len(X_train))
print("Testing Samples      :", len(X_test))
print("Number of Features   :", X.shape[1])
print("Number of Predictions:", len(predictions))

print("\nModel trained successfully.")

=======================================================
TASK 4: MODEL DEVELOPMENT & TRAINING COMPLETED
=======================================================
Dataset              : Iris Flower Dataset
Problem Type         : Multiclass Classification
Algorithm            : Random Forest Classifier
Number of Trees      : 100
Training Samples     : 119
Testing Samples      : 30
Number of Features   : 4
Number of Predictions: 30

Model trained successfully.

Model Development and Training Summary
The cleaned Iris dataset was divided into input features and a target variable. Sepal length, sepal width, petal length and petal width were used as the input features, while the Iris species was selected as the target.
The dataset was divided into 80% training data and 20% testing data. Stratified sampling was used to maintain a similar distribution of the three flower species in both datasets.
A Random Forest Classifier containing 100 decision trees was selected for the classification task. The model was trained using the training dataset, allowing it to learn relationships between flower measurements and their corresponding species.
After training, predictions were generated for the unseen test data. The trained model was also used to classify a new flower sample. Random Forest feature importance showed which flower measurements contributed most strongly to classification.
The actual model performance will be evaluated in Task 5 using classification metrics such as accuracy, precision, recall and a confusion matrix.