In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("student_performance.csv")

df

   Student_Name  Marks  Attendance
0         Aarav   78.0          92
1          Diya   65.0          85
2         Rohan   92.0          96
3        Ananya    NaN          78
4         Kabir   55.0          80
5          Isha   88.0          94
6         Arjun   34.0          68
7         Meera   72.0          88
8         Rahul   45.0          75
9         Sneha   81.0          91
10       Vikram   29.0          60
11        Pooja   67.0          86
12        Rohan   92.0          96
13       Ananya   74.0          89

In [3]:
df.head()

  Student_Name  Marks  Attendance
0        Aarav   78.0          92
1         Diya   65.0          85
2        Rohan   92.0          96
3       Ananya    NaN          78
4        Kabir   55.0          80

In [4]:
print("Rows and Columns:", df.shape)

Rows and Columns: (14, 3)

In [5]:
df.dtypes

Student_Name        str
Marks           float64
Attendance        int64
dtype: object

In [6]:
df.isnull().sum()

Student_Name    0
Marks           1
Attendance      0
dtype: int64

In [7]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 1
Duplicates after: 0

In [12]:
print(df.columns.tolist())

['Student_Name', 'Marks', 'Attendance']

In [15]:
features = ['Marks', 'Attendance']
target = 'Result'

In [20]:
df = pd.read_csv("student_performance.csv")
df = df.drop_duplicates()  # keep your existing duplicate removal

# NEW: fill missing Marks with the average
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

print("Missing values after cleaning:")
print(df.isnull().sum())  # should now show 0 for Marks

Missing values after cleaning:
Student_Name    0
Marks           0
Attendance      0
dtype: int64

In [16]:
df['Result'] = df['Marks'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')

features = ['Marks', 'Attendance']
target = 'Result'

X = df[features]
y = df[target]

print("Features (X):")
print(X)

print("\nTarget (y):")
print(y)

Features (X):
    Marks  Attendance
0    78.0          92
1    65.0          85
2    92.0          96
3     NaN          78
4    55.0          80
5    88.0          94
6    34.0          68
7    72.0          88
8    45.0          75
9    81.0          91
10   29.0          60
11   67.0          86
13   74.0          89

Target (y):
0     Pass
1     Pass
2     Pass
3     Fail
4     Pass
5     Pass
6     Fail
7     Pass
8     Pass
9     Pass
10    Fail
11    Pass
13    Pass
Name: Result, dtype: str

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (10, 2)
Testing data: (3, 2)

In [18]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!